### ISSUE TITLE
ActivityThread和SystemProperties包无法导入

### ISSUE THREAD

**Issue by uncletong** [huanglongyu/Demos#1]
您好，我在运行您的Graphic Demo时
为什么不能导入ActivityTread和SystemProperties

**Comment by huanglongyu** [comment]
在build.gradle里面 需要provided fileTree(dir: 'lib', include: 'android.jar')

**Comment by uncletong** [comment]
Hi，

太感谢了，我已经解决了。
对了，现在的版本好像更推荐用compile only代替provided。虽然我也不知道为什么，是ide提示的。分享给你。

Thank！
Best Regards.
